# This is a workflow for RSS feed to get started with Actions

name: Latest blog post workflow

# Controls when the action will run. 
on:
  # Run workflow automatically
  schedule: 
  # Runs every hour, on the hour
    - cron: '0 0 */5 * *'   
  
  # Allows you to run this workflow manually from the Actions tab
  # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# This workflow updates readme with blog
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@kannansi"
          max_post_count: 7
